### ISSUE TITLE
[Feature] Metamask / Blockchain Integration

### ISSUE THREAD

**Issue by vmohan7** [FusedVR/VRStreaming#13]
From a monetization perspective, it would be interesting to expose to the web wallet APIs for integration into the server

**Comment by Utopiah** [comment]
Definitely would be but limited since AFAIK the Oculus Browser does not allow add-ons. Firefox Reality did and had a test Coil build but unfortunately was deprecated.

**Comment by vmohan7** [comment]
@Utopiah check out the latest release. you can have a phone and VR headset connect to the same server and then authenticate transactions on your phone.
