### ISSUE TITLE
Add recommended Unity version to readme

### ISSUE THREAD

**Issue by andybak** [FusedVR/VRStreaming#24]
It might work on multiple versions but I always like to know the version that is most likely to just work.

The package.json mentions 2019.4. Is that right? Most people wouldn't think to look there.

**Comment by vmohan7** [comment]
Good point, will add to the README. I test this regularly with 2019 LTS, but have also verified with 2020 LTS. At some point, it would be good to write some github actions to run Render Streaming Unit Tests and compile tests against various versions too
