### ISSUE TITLE
an Issue from exporting Blockchain Testing into webgl 

### ISSUE THREAD

**Issue by hsjo12** [FusedVR/VRStreaming#32]
Hello, 

I am using my unity editor version  2020.3.24

I imported latest version 0.6.2 and 0.6.0 into my unity package at a different time to export Blockchain Testing into webgl. 

I did "check Allow 'unsafe' code" and  "turn on Lock Input to Game View in Options"

errors from 0.6.0
![image](https://user-images.githubusercontent.com/25118210/146582595-eb37dd43-8b0a-4eac-93a4-87209ea0a11a.png)

errors from 0.6.2
![image](https://user-images.githubusercontent.com/25118210/146582726-dc38ad60-17f0-4727-a132-f6fd122087c3.png)

Please help me..

**Comment by vmohan7** [comment]
Resolved on Discord. Looks like the issue was trying to make a WebGL build, which isn't supported
